export type categoryOptionsKOType =
  | '전체'
  | '디지털 기기'
  | '생활 가전'
  | '가구/인테리어'
  | '유아 도서'
  | '생활/가공 식품'
  | '스포츠/레저'
  | '여성 잡화'
  | '여성 의류'
  | '남성패션/잡화'
  | '게임/취미'
  | '뷰티/미용'
  | '반려 동물 용품'
  | '도서/티켓/음반'
  | '식물'
  | '기타 중고 물품';

export type categoryOptionsENType =
  | 'ALL'
  | 'DIGITAL_DEVICE'
  | 'HOUSEHOLD_APPLIANCE'
  | 'FURNITURE'
  | 'CHILDREN_BOOK'
  | 'FOOD'
  | 'SPORTS_LEISURE'
  | 'WOMAN_GOODS'
  | 'WOMAN_CLOTHES'
  | 'MAN_FASHION_GOODS'
  | 'HOBBY'
  | 'BEAUTY'
  | 'PET_SUPPLY'
  | 'BOOK_TICKET_RECORD'
  | 'PLANT'
  | 'ETC';
